/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.uam.azc.p_soft_omega.presentacion;

import mx.uam.azc.p_soft_omega.datos.Cliente;
import mx.uam.azc.p_soft_omega.datos.Pedido;
import mx.uam.azc.p_soft_omega.datos.Producto;
import mx.uam.azc.p_soft_omega.logica.AdministradorCliente;
import mx.uam.azc.p_soft_omega.logica.AdministradorPedido;
import mx.uam.azc.p_soft_omega.logica.AdministradorProducto;
import mx.uam.azc.p_soft_omega.servicios.ConexionMySQL;

/**
 *
 * @author Santiago PG
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameRegistrarPedido = new javax.swing.JFrame();
        lblRegistrarPedido = new javax.swing.JLabel();
        txtfClienteRP = new javax.swing.JTextField();
        btnComprobarClienteRP = new javax.swing.JButton();
        txtfProductoRP = new javax.swing.JTextField();
        btnComprobarProductoRP = new javax.swing.JButton();
        txtfCantidadRP = new javax.swing.JTextField();
        lblProductoPedidoRP = new javax.swing.JLabel();
        lblCantidadPedidoRP = new javax.swing.JLabel();
        lblPrecioProductoPedidoRP = new javax.swing.JLabel();
        scrpPedidosRP = new javax.swing.JScrollPane();
        lblTotalPedidoRP = new javax.swing.JLabel();
        btnAgregarProductoRP = new javax.swing.JButton();
        btnFinalizarPedidoRP = new javax.swing.JButton();
        btnRegresarRP = new javax.swing.JButton();
        lblNombreClienteRP = new javax.swing.JLabel();
        lblTelefonoClienteRP = new javax.swing.JLabel();
        lblDireccionClienteRP = new javax.swing.JLabel();
        lblNombreProductoRP = new javax.swing.JLabel();
        lblCantidadProductoRP = new javax.swing.JLabel();
        lblPrecioProductoRP = new javax.swing.JLabel();
        lblDineroProductoRP = new javax.swing.JLabel();
        lblPrecioPedidoRP = new javax.swing.JLabel();
        lblDineroPedidoRP = new javax.swing.JLabel();
        FrameRegistrarCliente = new javax.swing.JFrame();
        lblRegistrarCliente = new javax.swing.JLabel();
        lblNombreRC = new javax.swing.JLabel();
        txtfNombreRC = new javax.swing.JTextField();
        lblTelefonoRC = new javax.swing.JLabel();
        txtfTelefonoRC = new javax.swing.JTextField();
        txtfDireccionRC = new javax.swing.JTextField();
        lblDireccionRC = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnRegresarRC = new javax.swing.JButton();
        lblNumeroIdentificacionRC = new javax.swing.JLabel();
        FrameCancelarPedido = new javax.swing.JFrame();
        lblCancelarPedido = new javax.swing.JLabel();
        txtfClienteCP = new javax.swing.JTextField();
        btnBuscarClienteCP = new javax.swing.JButton();
        scrpPedidosCP = new javax.swing.JScrollPane();
        btnCancelarPedido = new javax.swing.JButton();
        btnRegresarCP = new javax.swing.JButton();
        txtfPedidoCancelarCP = new javax.swing.JTextField();
        FrameGenerarReporte = new javax.swing.JFrame();
        lblGenerarReporte = new javax.swing.JLabel();
        cmbbPeriodoGR = new javax.swing.JComboBox<>();
        lblPeriodoRevisarGR = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnRegresarGR = new javax.swing.JButton();
        FrameEditarPedido = new javax.swing.JFrame();
        lblEditarPedido = new javax.swing.JLabel();
        txtfClienteEP = new javax.swing.JTextField();
        btnBuscarClienteEP = new javax.swing.JButton();
        scrpPedidosEP = new javax.swing.JScrollPane();
        txtfEliminarProductoEP = new javax.swing.JTextField();
        btnEliminarProductoEP = new javax.swing.JButton();
        txtfAgregarProductoEP = new javax.swing.JTextField();
        txtfCantidadProductoEP = new javax.swing.JTextField();
        btnAgregarProductoEP = new javax.swing.JButton();
        btnRegresarEP = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        btnFrameRegistrarPedido = new javax.swing.JButton();
        btnFrameRegistrarCliente = new javax.swing.JButton();
        btnFrameCancelarPedido = new javax.swing.JButton();
        btnFrameGenerarReporte = new javax.swing.JButton();
        btnFrameEditarPedido = new javax.swing.JButton();

        lblRegistrarPedido.setText("Registro de Pedido");

        txtfClienteRP.setText("Identificador de Cliente");
        txtfClienteRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteRPActionPerformed(evt);
            }
        });

        btnComprobarClienteRP.setText("Comprobar");
        btnComprobarClienteRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarClienteRPActionPerformed(evt);
            }
        });

        txtfProductoRP.setText("Identificador de Producto a agregar");
        txtfProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfProductoRPActionPerformed(evt);
            }
        });

        btnComprobarProductoRP.setText("Comprobar");
        btnComprobarProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarProductoRPActionPerformed(evt);
            }
        });

        txtfCantidadRP.setText("Ingresa cantidad");

        lblProductoPedidoRP.setText("Producto");

        lblCantidadPedidoRP.setText("Cantidad");

        lblPrecioProductoPedidoRP.setText("Precio");

        lblTotalPedidoRP.setText("Total:");

        btnAgregarProductoRP.setText("Agregar Producto");
        btnAgregarProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoRPActionPerformed(evt);
            }
        });

        btnFinalizarPedidoRP.setText("Finalizar Pedido");
        btnFinalizarPedidoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoRPActionPerformed(evt);
            }
        });

        btnRegresarRP.setText("Regresar");
        btnRegresarRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRPActionPerformed(evt);
            }
        });

        lblNombreClienteRP.setText("Nombre");

        lblTelefonoClienteRP.setText("Telefono");

        lblDireccionClienteRP.setText("Direccion");

        lblNombreProductoRP.setText("Nombre");

        lblCantidadProductoRP.setText("Cantidad");

        lblPrecioProductoRP.setText("Precio");

        lblDineroProductoRP.setText("$");

        lblPrecioPedidoRP.setText("Precio");

        lblDineroPedidoRP.setText("$");

        javax.swing.GroupLayout FrameRegistrarPedidoLayout = new javax.swing.GroupLayout(FrameRegistrarPedido.getContentPane());
        FrameRegistrarPedido.getContentPane().setLayout(FrameRegistrarPedidoLayout);
        FrameRegistrarPedidoLayout.setHorizontalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addComponent(txtfClienteRP)
                                .addGap(18, 18, 18)
                                .addComponent(btnComprobarClienteRP))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(lblProductoPedidoRP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadPedidoRP))
                                    .addComponent(txtfProductoRP)
                                    .addComponent(txtfCantidadRP, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregarProductoRP, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                                    .addComponent(lblDineroProductoRP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblPrecioProductoRP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnComprobarProductoRP))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrecioProductoPedidoRP)
                                        .addGap(32, 32, 32))))
                            .addComponent(scrpPedidosRP)
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addComponent(btnRegresarRP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinalizarPedidoRP))
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidadProductoRP)
                                    .addComponent(lblNombreProductoRP)
                                    .addComponent(lblNombreClienteRP)
                                    .addComponent(lblTelefonoClienteRP)
                                    .addComponent(lblDireccionClienteRP))
                                .addGap(0, 368, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalPedidoRP)
                        .addGap(105, 105, 105)
                        .addComponent(lblDineroPedidoRP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecioPedidoRP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistrarPedido)
                .addGap(167, 167, 167))
        );
        FrameRegistrarPedidoLayout.setVerticalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblRegistrarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobarClienteRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreClienteRP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefonoClienteRP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccionClienteRP)
                .addGap(23, 23, 23)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprobarProductoRP)
                    .addComponent(txtfProductoRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProductoRP)
                    .addComponent(lblPrecioProductoRP)
                    .addComponent(lblDineroProductoRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadProductoRP)
                .addGap(25, 25, 25)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCantidadRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProductoRP))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoPedidoRP)
                    .addComponent(lblCantidadPedidoRP)
                    .addComponent(lblPrecioProductoPedidoRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosRP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPedidoRP)
                    .addComponent(lblPrecioPedidoRP)
                    .addComponent(lblDineroPedidoRP))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarPedidoRP)
                    .addComponent(btnRegresarRP))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblRegistrarCliente.setText("Registro de Cliente");

        lblNombreRC.setText("Nombre:");

        lblTelefonoRC.setText("Teléfono:");

        lblDireccionRC.setText("Dirección:");

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnRegresarRC.setText("Regresar");
        btnRegresarRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRCActionPerformed(evt);
            }
        });

        lblNumeroIdentificacionRC.setText("Número de identificación");

        javax.swing.GroupLayout FrameRegistrarClienteLayout = new javax.swing.GroupLayout(FrameRegistrarCliente.getContentPane());
        FrameRegistrarCliente.getContentPane().setLayout(FrameRegistrarClienteLayout);
        FrameRegistrarClienteLayout.setHorizontalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreRC)
                                    .addComponent(lblTelefonoRC))
                                .addGap(18, 18, 18)
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfTelefonoRC)
                                    .addComponent(txtfNombreRC)))
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addComponent(lblDireccionRC)
                                .addGap(18, 18, 18)
                                .addComponent(txtfDireccionRC))))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumeroIdentificacionRC)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(lblRegistrarCliente)
                        .addGap(157, 157, 157))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addComponent(btnRegresarRC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarCliente)
                        .addContainerGap())))
        );
        FrameRegistrarClienteLayout.setVerticalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarCliente)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRC)
                    .addComponent(txtfNombreRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoRC)
                    .addComponent(txtfTelefonoRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionRC)
                    .addComponent(txtfDireccionRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNumeroIdentificacionRC)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarRC)
                    .addComponent(btnRegistrarCliente))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        lblCancelarPedido.setText("Cancelación de Pedido");

        txtfClienteCP.setText("Identificador del cliente");
        txtfClienteCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteCPActionPerformed(evt);
            }
        });

        btnBuscarClienteCP.setText("Buscar");
        btnBuscarClienteCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteCPActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnRegresarCP.setText("Regresar");
        btnRegresarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCPActionPerformed(evt);
            }
        });

        txtfPedidoCancelarCP.setText("Clave de pedido a cancelar");

        javax.swing.GroupLayout FrameCancelarPedidoLayout = new javax.swing.GroupLayout(FrameCancelarPedido.getContentPane());
        FrameCancelarPedido.getContentPane().setLayout(FrameCancelarPedidoLayout);
        FrameCancelarPedidoLayout.setHorizontalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                                .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarClienteCP)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrpPedidosCP)))
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblCancelarPedido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresarCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido)))
                .addContainerGap())
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtfPedidoCancelarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameCancelarPedidoLayout.setVerticalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtfPedidoCancelarCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarCP)
                    .addComponent(btnCancelarPedido))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        lblGenerarReporte.setText("Generación de Reporte");

        cmbbPeriodoGR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbPeriodoGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbPeriodoGRActionPerformed(evt);
            }
        });

        lblPeriodoRevisarGR.setText("Periodo a revisar:");

        btnGenerarReporte.setText("Generar reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnRegresarGR.setText("Regresar");
        btnRegresarGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarGRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameGenerarReporteLayout = new javax.swing.GroupLayout(FrameGenerarReporte.getContentPane());
        FrameGenerarReporte.getContentPane().setLayout(FrameGenerarReporteLayout);
        FrameGenerarReporteLayout.setHorizontalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPeriodoRevisarGR)
                        .addGap(18, 18, 18)
                        .addComponent(cmbbPeriodoGR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblGenerarReporte)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegresarGR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte)))
                .addContainerGap())
        );
        FrameGenerarReporteLayout.setVerticalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGenerarReporte)
                .addGap(18, 18, 18)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbPeriodoGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeriodoRevisarGR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarReporte)
                    .addComponent(btnRegresarGR))
                .addContainerGap())
        );

        lblEditarPedido.setText("Editar Pedido");

        txtfClienteEP.setText("Escribir el número del cliente");
        txtfClienteEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteEPActionPerformed(evt);
            }
        });

        btnBuscarClienteEP.setText("Buscar");

        txtfEliminarProductoEP.setText("Clave de producto a eliminar (opcional)");

        btnEliminarProductoEP.setText("Eliminar producto");

        txtfAgregarProductoEP.setText("Clave de producto a agregar (opcional)");

        txtfCantidadProductoEP.setText("Cantidad (opcional)");

        btnAgregarProductoEP.setText("Agregar producto");

        btnRegresarEP.setText("Regresar");
        btnRegresarEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameEditarPedidoLayout = new javax.swing.GroupLayout(FrameEditarPedido.getContentPane());
        FrameEditarPedido.getContentPane().setLayout(FrameEditarPedidoLayout);
        FrameEditarPedidoLayout.setHorizontalGroup(
            FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                        .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lblEditarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtfClienteEP)
                                .addGap(18, 18, 18)))
                        .addComponent(btnBuscarClienteEP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrpPedidosEP)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEditarPedidoLayout.createSequentialGroup()
                                .addComponent(btnRegresarEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarProductoEP))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEditarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfEliminarProductoEP)
                                    .addComponent(txtfAgregarProductoEP, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfCantidadProductoEP)
                                    .addComponent(btnEliminarProductoEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        FrameEditarPedidoLayout.setVerticalGroup(
            FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfEliminarProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProductoEP))
                .addGap(19, 19, 19)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCantidadProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAgregarProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProductoEP)
                    .addComponent(btnRegresarEP))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setText("Menu inicial");

        btnFrameRegistrarPedido.setText("Registrar Pedido");
        btnFrameRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarPedidoActionPerformed(evt);
            }
        });

        btnFrameRegistrarCliente.setText("Registrar Cliente");
        btnFrameRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarClienteActionPerformed(evt);
            }
        });

        btnFrameCancelarPedido.setText("Cancelar Pedido");
        btnFrameCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameCancelarPedidoActionPerformed(evt);
            }
        });

        btnFrameGenerarReporte.setText("Generar reporte de Pedido");
        btnFrameGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameGenerarReporteActionPerformed(evt);
            }
        });

        btnFrameEditarPedido.setText("Editar Pedido");
        btnFrameEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameEditarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMenu)
                    .addComponent(btnFrameRegistrarPedido)
                    .addComponent(btnFrameRegistrarCliente)
                    .addComponent(btnFrameCancelarPedido)
                    .addComponent(btnFrameGenerarReporte)
                    .addComponent(btnFrameEditarPedido))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarCliente)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameCancelarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameEditarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameGenerarReporte)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrameRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        FrameRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarPedidoActionPerformed

    private void btnFrameRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarClienteActionPerformed
        // TODO add your handling code here:
        FrameRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarClienteActionPerformed

    private void btnFrameCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameCancelarPedidoActionPerformed
        // TODO add your handling code here:
        FrameCancelarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameCancelarPedidoActionPerformed

    private void btnFrameGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameGenerarReporteActionPerformed
        // TODO add your handling code here:
        FrameGenerarReporte.setVisible(true);
    }//GEN-LAST:event_btnFrameGenerarReporteActionPerformed

    private void txtfClienteRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteRPActionPerformed

    private void txtfClienteCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteCPActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void cmbbPeriodoGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbPeriodoGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbPeriodoGRActionPerformed

    private void btnFrameEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameEditarPedidoActionPerformed
        // TODO add your handling code here:
        FrameEditarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameEditarPedidoActionPerformed

    private void txtfClienteEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteEPActionPerformed

    private void txtfProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProductoRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProductoRPActionPerformed

    private void btnRegresarRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRCActionPerformed
        // TODO add your handling code here:
        FrameRegistrarCliente.setVisible(false);
    }//GEN-LAST:event_btnRegresarRCActionPerformed

    private void btnRegresarRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRPActionPerformed
        // TODO add your handling code here:
        FrameRegistrarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarRPActionPerformed

    private void btnRegresarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCPActionPerformed
        // TODO add your handling code here:
        FrameCancelarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarCPActionPerformed

    private void btnRegresarGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarGRActionPerformed
        // TODO add your handling code here:
        FrameGenerarReporte.setVisible(false);
    }//GEN-LAST:event_btnRegresarGRActionPerformed

    private void btnRegresarEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEPActionPerformed
        // TODO add your handling code here:
        FrameEditarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarEPActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente.setNombre(txtfNombreRC.getText());
        cliente.setDireccion(txtfDireccionRC.getText());
        cliente.setTelefono(txtfTelefonoRC.getText());
        cliente.setClave(txtfTelefonoRC.getText());
        
        // INSERTAR CLIENTE A BD
        
        lblNumeroIdentificacionRC.setText("Número de identificación: "+cliente.getClave());
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnComprobarClienteRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarClienteRPActionPerformed
        // TODO add your handling code here:
        String idCliente = txtfClienteRP.getText();
        Cliente cliente = new Cliente();
        
        //BUSCAR EL CLIENTE EN LA BD
        
        lblNombreClienteRP.setText(cliente.getNombre());
        lblTelefonoClienteRP.setText(cliente.getTelefono());
        lblDireccionClienteRP.setText(cliente.getDireccion());
    }//GEN-LAST:event_btnComprobarClienteRPActionPerformed

    private void btnComprobarProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarProductoRPActionPerformed
        // TODO add your handling code here:
        String idProducto = txtfProductoRP.getText();
        Producto producto = new Producto();
        
        //BUSCAR EL PRODUCTO EN LA BD
        
        lblNombreProductoRP.setText(producto.getNombre());
        lblCantidadProductoRP.setText(Integer.toString(producto.getCantidad()));
        lblPrecioProductoRP.setText(Integer.toString(producto.getPrecio()));
    }//GEN-LAST:event_btnComprobarProductoRPActionPerformed

    private void btnAgregarProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoRPActionPerformed

    private void btnFinalizarPedidoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarPedidoRPActionPerformed

    private void btnBuscarClienteCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteCPActionPerformed
        // TODO add your handling code here:
        String idCliente = txtfClienteCP.getText();
        
        //BUSCAR PEDIDOS QUE TENGA EL CLIENTE EN LA BD
        
        
    }//GEN-LAST:event_btnBuscarClienteCPActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
        String idPedido = txtfPedidoCancelarCP.getText();
        
        //ELIMINAR PEDIDO DE LA BASE DE DATOS
        
        
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }
    
    AdministradorCliente adminCliente = new AdministradorCliente(new ConexionMySQL());
    AdministradorPedido adminPedido = new AdministradorPedido(new ConexionMySQL());
    AdministradorProducto adminProducto = new AdministradorProducto(new ConexionMySQL());

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameCancelarPedido;
    private javax.swing.JFrame FrameEditarPedido;
    private javax.swing.JFrame FrameGenerarReporte;
    private javax.swing.JFrame FrameRegistrarCliente;
    private javax.swing.JFrame FrameRegistrarPedido;
    private javax.swing.JButton btnAgregarProductoEP;
    private javax.swing.JButton btnAgregarProductoRP;
    private javax.swing.JButton btnBuscarClienteCP;
    private javax.swing.JButton btnBuscarClienteEP;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnComprobarClienteRP;
    private javax.swing.JButton btnComprobarProductoRP;
    private javax.swing.JButton btnEliminarProductoEP;
    private javax.swing.JButton btnFinalizarPedidoRP;
    private javax.swing.JButton btnFrameCancelarPedido;
    private javax.swing.JButton btnFrameEditarPedido;
    private javax.swing.JButton btnFrameGenerarReporte;
    private javax.swing.JButton btnFrameRegistrarCliente;
    private javax.swing.JButton btnFrameRegistrarPedido;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegresarCP;
    private javax.swing.JButton btnRegresarEP;
    private javax.swing.JButton btnRegresarGR;
    private javax.swing.JButton btnRegresarRC;
    private javax.swing.JButton btnRegresarRP;
    private javax.swing.JComboBox<String> cmbbPeriodoGR;
    private javax.swing.JLabel lblCancelarPedido;
    private javax.swing.JLabel lblCantidadPedidoRP;
    private javax.swing.JLabel lblCantidadProductoRP;
    private javax.swing.JLabel lblDineroPedidoRP;
    private javax.swing.JLabel lblDineroProductoRP;
    private javax.swing.JLabel lblDireccionClienteRP;
    private javax.swing.JLabel lblDireccionRC;
    private javax.swing.JLabel lblEditarPedido;
    private javax.swing.JLabel lblGenerarReporte;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreClienteRP;
    private javax.swing.JLabel lblNombreProductoRP;
    private javax.swing.JLabel lblNombreRC;
    private javax.swing.JLabel lblNumeroIdentificacionRC;
    private javax.swing.JLabel lblPeriodoRevisarGR;
    private javax.swing.JLabel lblPrecioPedidoRP;
    private javax.swing.JLabel lblPrecioProductoPedidoRP;
    private javax.swing.JLabel lblPrecioProductoRP;
    private javax.swing.JLabel lblProductoPedidoRP;
    private javax.swing.JLabel lblRegistrarCliente;
    private javax.swing.JLabel lblRegistrarPedido;
    private javax.swing.JLabel lblTelefonoClienteRP;
    private javax.swing.JLabel lblTelefonoRC;
    private javax.swing.JLabel lblTotalPedidoRP;
    private javax.swing.JScrollPane scrpPedidosCP;
    private javax.swing.JScrollPane scrpPedidosEP;
    private javax.swing.JScrollPane scrpPedidosRP;
    private javax.swing.JTextField txtfAgregarProductoEP;
    private javax.swing.JTextField txtfCantidadProductoEP;
    private javax.swing.JTextField txtfCantidadRP;
    private javax.swing.JTextField txtfClienteCP;
    private javax.swing.JTextField txtfClienteEP;
    private javax.swing.JTextField txtfClienteRP;
    private javax.swing.JTextField txtfDireccionRC;
    private javax.swing.JTextField txtfEliminarProductoEP;
    private javax.swing.JTextField txtfNombreRC;
    private javax.swing.JTextField txtfPedidoCancelarCP;
    private javax.swing.JTextField txtfProductoRP;
    private javax.swing.JTextField txtfTelefonoRC;
    // End of variables declaration//GEN-END:variables

}
