/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.uam.azc.p_soft_omega.presentacion;

import mx.uam.azc.p_soft_omega.datos.Cliente;
import mx.uam.azc.p_soft_omega.datos.Pedido;
import mx.uam.azc.p_soft_omega.datos.Producto;
import java.util.ArrayList;

/**
 *
 * @author Santiago PG
 */
public class MenuJFrame extends javax.swing.JFrame {
    
    private static final int WIDTH = 450;
    private static final int HEIGHT = 350;
    
    ArrayList<Cliente> clientes = new ArrayList<Cliente>();
    ArrayList<Producto> productos = new ArrayList<Producto>();
    String[] nombreProducto = {"Coca Cola", "Doritos", "Tostitos", "Chocoroles", "Cigarros",
                               "Paleta Magnum", "Panditas", "Carlos V", "Cerveza", "Jamon",
                               "Queso", "Tortillas", "Huevo", "Pan", "Agua"};
    int[] precioProducto = {30, 15, 20, 13, 60,
                            30, 10, 7, 90, 25,
                            25, 12, 18, 33, 13};
    ArrayList<Pedido> pedidos = new ArrayList<Pedido>();
    //int numProdPedido = 0;
    int clavePedidos = 0;

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
        
        
        for(int i=0; i<nombreProducto.length; ++i) {
            Producto producto = new Producto();
            producto.setClave(Integer.toString(i+1));
            producto.setNombre(nombreProducto[i]);
            producto.setPrecio(precioProducto[i]);
            producto.setCantidad(20);
            
            productos.add(producto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameRegistrarPedido = new javax.swing.JFrame();
        lblRegistrarPedido = new javax.swing.JLabel();
        txtfClienteRP = new javax.swing.JTextField();
        btnComprobarClienteRP = new javax.swing.JButton();
        txtfProductoRP = new javax.swing.JTextField();
        btnComprobarProductoRP = new javax.swing.JButton();
        txtfCantidadRP = new javax.swing.JTextField();
        lblProductoPedidoRP = new javax.swing.JLabel();
        lblCantidadPedidoRP = new javax.swing.JLabel();
        lblPrecioProductoPedidoRP = new javax.swing.JLabel();
        scrpPedidosRP = new javax.swing.JScrollPane();
        txtaPedidosRP = new javax.swing.JTextArea();
        lblTotalPedidoRP = new javax.swing.JLabel();
        btnAgregarProductoRP = new javax.swing.JButton();
        btnRegistrarPedidoRP = new javax.swing.JButton();
        btnRegresarRP = new javax.swing.JButton();
        lblNombreClienteRP = new javax.swing.JLabel();
        lblTelefonoClienteRP = new javax.swing.JLabel();
        lblDireccionClienteRP = new javax.swing.JLabel();
        lblNombreProductoRP = new javax.swing.JLabel();
        lblCantidadProductoRP = new javax.swing.JLabel();
        lblPrecioProductoRP = new javax.swing.JLabel();
        lblDineroProductoRP = new javax.swing.JLabel();
        lblPrecioPedidoRP = new javax.swing.JLabel();
        lblDineroPedidoRP = new javax.swing.JLabel();
        lblIdentificadorPedidoRP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FrameRegistrarCliente = new javax.swing.JFrame();
        lblRegistrarCliente = new javax.swing.JLabel();
        lblNombreRC = new javax.swing.JLabel();
        txtfNombreRC = new javax.swing.JTextField();
        lblTelefonoRC = new javax.swing.JLabel();
        txtfTelefonoRC = new javax.swing.JTextField();
        txtfDireccionRC = new javax.swing.JTextField();
        lblDireccionRC = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnRegresarRC = new javax.swing.JButton();
        lblNumeroIdentificacionRC = new javax.swing.JLabel();
        FrameCancelarPedido = new javax.swing.JFrame();
        lblCancelarPedido = new javax.swing.JLabel();
        txtfClienteCP = new javax.swing.JTextField();
        btnBuscarClienteCP = new javax.swing.JButton();
        scrpPedidosCP = new javax.swing.JScrollPane();
        txtaPedidosCP = new javax.swing.JTextArea();
        btnCancelarPedido = new javax.swing.JButton();
        btnRegresarCP = new javax.swing.JButton();
        txtfPedidoCancelarCP = new javax.swing.JTextField();
        FrameGenerarReporte = new javax.swing.JFrame();
        lblGenerarReporte = new javax.swing.JLabel();
        cmbbPeriodoGR = new javax.swing.JComboBox<>();
        lblPeriodoRevisarGR = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnRegresarGR = new javax.swing.JButton();
        FrameEditarPedido = new javax.swing.JFrame();
        lblEditarPedido = new javax.swing.JLabel();
        txtfPedidoEP = new javax.swing.JTextField();
        btnBuscarPedidoEP = new javax.swing.JButton();
        scrpPedidoEP = new javax.swing.JScrollPane();
        txtaPedidoEP = new javax.swing.JTextArea();
        txtfEliminarProductoEP = new javax.swing.JTextField();
        btnEliminarProductoEP = new javax.swing.JButton();
        txtfAgregarProductoEP = new javax.swing.JTextField();
        txtfCantidadProductoEP = new javax.swing.JTextField();
        btnAgregarProductoEP = new javax.swing.JButton();
        btnRegresarEP = new javax.swing.JButton();
        FrameFinalizarPedido = new javax.swing.JFrame();
        lblFinalizarPedido = new javax.swing.JLabel();
        txtfPedidoFP = new javax.swing.JTextField();
        btnBuscarPedidoFP = new javax.swing.JButton();
        scrpPedidoFP = new javax.swing.JScrollPane();
        txtaPedidoFP = new javax.swing.JTextArea();
        btnFinalizarPedidoFP = new javax.swing.JButton();
        btnRegresarFP = new javax.swing.JButton();
        FramePedidosPendientes = new javax.swing.JFrame();
        lblPedidosPendientes = new javax.swing.JLabel();
        scrpPedidosPP = new javax.swing.JScrollPane();
        txtaPedidosPP = new javax.swing.JTextArea();
        btnRegresarPP = new javax.swing.JButton();
        txtfPedidoRevisarPP = new javax.swing.JTextField();
        btnRevisarPP = new javax.swing.JButton();
        lblPedidoRevisarPP = new javax.swing.JLabel();
        btnRegresarPedidosPP = new javax.swing.JButton();
        btnEnviadoPP = new javax.swing.JButton();
        lblPedidoEnviarPP = new javax.swing.JLabel();
        txtfPedidoEnviarPP = new javax.swing.JTextField();
        lblMenu = new javax.swing.JLabel();
        btnFrameRegistrarPedido = new javax.swing.JButton();
        btnFrameRegistrarCliente = new javax.swing.JButton();
        btnFrameCancelarPedido = new javax.swing.JButton();
        btnFrameGenerarReporte = new javax.swing.JButton();
        btnFrameEditarPedido = new javax.swing.JButton();
        btnFrameFinalizarPedido = new javax.swing.JButton();
        btnFramePedidosPendientes = new javax.swing.JButton();

        lblRegistrarPedido.setText("Registro de Pedido");

        txtfClienteRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteRPActionPerformed(evt);
            }
        });

        btnComprobarClienteRP.setText("Comprobar");
        btnComprobarClienteRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarClienteRPActionPerformed(evt);
            }
        });

        txtfProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfProductoRPActionPerformed(evt);
            }
        });

        btnComprobarProductoRP.setText("Comprobar");
        btnComprobarProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarProductoRPActionPerformed(evt);
            }
        });

        txtfCantidadRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCantidadRPActionPerformed(evt);
            }
        });

        lblProductoPedidoRP.setText("Producto");

        lblCantidadPedidoRP.setText("Cantidad");

        lblPrecioProductoPedidoRP.setText("Precio");

        txtaPedidosRP.setColumns(20);
        txtaPedidosRP.setRows(5);
        scrpPedidosRP.setViewportView(txtaPedidosRP);

        lblTotalPedidoRP.setText("Total:");

        btnAgregarProductoRP.setText("Agregar Producto");
        btnAgregarProductoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoRPActionPerformed(evt);
            }
        });

        btnRegistrarPedidoRP.setText("Registrar Pedido");
        btnRegistrarPedidoRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedidoRPActionPerformed(evt);
            }
        });

        btnRegresarRP.setText("Regresar");
        btnRegresarRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRPActionPerformed(evt);
            }
        });

        lblNombreClienteRP.setText("Nombre:");

        lblTelefonoClienteRP.setText("Teléfono:");

        lblDireccionClienteRP.setText("Dirección:");

        lblNombreProductoRP.setText("Nombre:");

        lblCantidadProductoRP.setText("Stock:");

        lblPrecioProductoRP.setText("Precio");

        lblDineroProductoRP.setText("$");

        lblPrecioPedidoRP.setText("Precio");

        lblDineroPedidoRP.setText("$");

        lblIdentificadorPedidoRP.setText("Identificador del Pedido:");

        jLabel1.setText("Identificador Cliente");

        jLabel2.setText("Identificador  Producto");

        jLabel3.setText("Cantidad a agregar");

        jButton1.setText("Nuevo Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameRegistrarPedidoLayout = new javax.swing.GroupLayout(FrameRegistrarPedido.getContentPane());
        FrameRegistrarPedido.getContentPane().setLayout(FrameRegistrarPedidoLayout);
        FrameRegistrarPedidoLayout.setHorizontalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrpPedidosRP)
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidadProductoRP)
                                    .addComponent(lblNombreProductoRP)
                                    .addComponent(lblNombreClienteRP)
                                    .addComponent(lblTelefonoClienteRP)
                                    .addComponent(lblDireccionClienteRP))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(lblProductoPedidoRP)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfClienteRP)
                                    .addComponent(txtfProductoRP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(lblCantidadPedidoRP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(lblPrecioProductoPedidoRP))
                                    .addComponent(txtfCantidadRP, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarProductoRP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                            .addComponent(lblDineroProductoRP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblPrecioProductoRP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnComprobarProductoRP))
                                    .addComponent(btnComprobarClienteRP, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalPedidoRP)
                        .addGap(105, 105, 105)
                        .addComponent(lblDineroPedidoRP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecioPedidoRP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistrarPedido)
                .addGap(167, 167, 167))
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addComponent(btnRegresarRP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(btnRegistrarPedidoRP))
                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addComponent(lblIdentificadorPedidoRP)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FrameRegistrarPedidoLayout.setVerticalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblRegistrarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobarClienteRP)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreClienteRP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefonoClienteRP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccionClienteRP)
                .addGap(23, 23, 23)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprobarProductoRP)
                    .addComponent(txtfProductoRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProductoRP)
                    .addComponent(lblPrecioProductoRP)
                    .addComponent(lblDineroProductoRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadProductoRP)
                .addGap(25, 25, 25)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCantidadRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProductoRP)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductoPedidoRP)
                    .addComponent(lblCantidadPedidoRP)
                    .addComponent(lblPrecioProductoPedidoRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosRP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPedidoRP)
                    .addComponent(lblPrecioPedidoRP)
                    .addComponent(lblDineroPedidoRP))
                .addGap(18, 18, 18)
                .addComponent(lblIdentificadorPedidoRP)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarRP)
                    .addComponent(btnRegistrarPedidoRP)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblRegistrarCliente.setText("Registro de Cliente");

        lblNombreRC.setText("Nombre:");

        lblTelefonoRC.setText("Teléfono:");

        lblDireccionRC.setText("Dirección:");

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnRegresarRC.setText("Regresar");
        btnRegresarRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarRCActionPerformed(evt);
            }
        });

        lblNumeroIdentificacionRC.setText("Número identificador:");

        javax.swing.GroupLayout FrameRegistrarClienteLayout = new javax.swing.GroupLayout(FrameRegistrarCliente.getContentPane());
        FrameRegistrarCliente.getContentPane().setLayout(FrameRegistrarClienteLayout);
        FrameRegistrarClienteLayout.setHorizontalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreRC)
                                    .addComponent(lblTelefonoRC))
                                .addGap(18, 18, 18)
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfTelefonoRC)
                                    .addComponent(txtfNombreRC)))
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addComponent(lblDireccionRC)
                                .addGap(18, 18, 18)
                                .addComponent(txtfDireccionRC))))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumeroIdentificacionRC)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(lblRegistrarCliente)
                        .addGap(157, 157, 157))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addComponent(btnRegresarRC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarCliente)
                        .addContainerGap())))
        );
        FrameRegistrarClienteLayout.setVerticalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarCliente)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRC)
                    .addComponent(txtfNombreRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoRC)
                    .addComponent(txtfTelefonoRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionRC)
                    .addComponent(txtfDireccionRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNumeroIdentificacionRC)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarRC)
                    .addComponent(btnRegistrarCliente))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        lblCancelarPedido.setText("Cancelación de Pedido");

        txtfClienteCP.setText("Identificador del cliente");
        txtfClienteCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteCPActionPerformed(evt);
            }
        });

        btnBuscarClienteCP.setText("Buscar");
        btnBuscarClienteCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteCPActionPerformed(evt);
            }
        });

        txtaPedidosCP.setColumns(20);
        txtaPedidosCP.setRows(5);
        scrpPedidosCP.setViewportView(txtaPedidosCP);

        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnRegresarCP.setText("Regresar");
        btnRegresarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCPActionPerformed(evt);
            }
        });

        txtfPedidoCancelarCP.setText("Clave de pedido a cancelar");

        javax.swing.GroupLayout FrameCancelarPedidoLayout = new javax.swing.GroupLayout(FrameCancelarPedido.getContentPane());
        FrameCancelarPedido.getContentPane().setLayout(FrameCancelarPedidoLayout);
        FrameCancelarPedidoLayout.setHorizontalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(lblCancelarPedido))
                            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtfPedidoCancelarCP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                                .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarClienteCP)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrpPedidosCP)
                            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                                .addComponent(btnRegresarCP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarPedido)))))
                .addContainerGap())
        );
        FrameCancelarPedidoLayout.setVerticalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosCP, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtfPedidoCancelarCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarCP)
                    .addComponent(btnCancelarPedido))
                .addContainerGap())
        );

        lblGenerarReporte.setText("Generación de Reporte");

        cmbbPeriodoGR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbPeriodoGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbPeriodoGRActionPerformed(evt);
            }
        });

        lblPeriodoRevisarGR.setText("Periodo a revisar:");

        btnGenerarReporte.setText("Generar reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnRegresarGR.setText("Regresar");
        btnRegresarGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarGRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameGenerarReporteLayout = new javax.swing.GroupLayout(FrameGenerarReporte.getContentPane());
        FrameGenerarReporte.getContentPane().setLayout(FrameGenerarReporteLayout);
        FrameGenerarReporteLayout.setHorizontalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPeriodoRevisarGR)
                        .addGap(18, 18, 18)
                        .addComponent(cmbbPeriodoGR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblGenerarReporte)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegresarGR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte)))
                .addContainerGap())
        );
        FrameGenerarReporteLayout.setVerticalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGenerarReporte)
                .addGap(18, 18, 18)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbPeriodoGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeriodoRevisarGR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarReporte)
                    .addComponent(btnRegresarGR))
                .addContainerGap())
        );

        lblEditarPedido.setText("Editar Pedido");

        txtfPedidoEP.setText("Escribir el identificador del pedido");
        txtfPedidoEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPedidoEPActionPerformed(evt);
            }
        });

        btnBuscarPedidoEP.setText("Buscar");

        txtaPedidoEP.setColumns(20);
        txtaPedidoEP.setRows(5);
        scrpPedidoEP.setViewportView(txtaPedidoEP);

        txtfEliminarProductoEP.setText("Clave de producto a eliminar (opcional)");

        btnEliminarProductoEP.setText("Eliminar producto");

        txtfAgregarProductoEP.setText("Clave de producto a agregar (opcional)");

        txtfCantidadProductoEP.setText("Cantidad (opcional)");

        btnAgregarProductoEP.setText("Agregar producto");

        btnRegresarEP.setText("Regresar");
        btnRegresarEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameEditarPedidoLayout = new javax.swing.GroupLayout(FrameEditarPedido.getContentPane());
        FrameEditarPedido.getContentPane().setLayout(FrameEditarPedidoLayout);
        FrameEditarPedidoLayout.setHorizontalGroup(
            FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                        .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lblEditarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtfPedidoEP)
                                .addGap(18, 18, 18)))
                        .addComponent(btnBuscarPedidoEP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrpPedidoEP)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEditarPedidoLayout.createSequentialGroup()
                                .addComponent(btnRegresarEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarProductoEP))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameEditarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfEliminarProductoEP)
                                    .addComponent(txtfAgregarProductoEP, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfCantidadProductoEP)
                                    .addComponent(btnEliminarProductoEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        FrameEditarPedidoLayout.setVerticalGroup(
            FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameEditarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfPedidoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPedidoEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidoEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfEliminarProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProductoEP))
                .addGap(19, 19, 19)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCantidadProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAgregarProductoEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(FrameEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProductoEP)
                    .addComponent(btnRegresarEP))
                .addContainerGap())
        );

        lblFinalizarPedido.setText("Finalizar Pedido");

        txtfPedidoFP.setText("Identificador del pedido");
        txtfPedidoFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPedidoFPActionPerformed(evt);
            }
        });

        btnBuscarPedidoFP.setText("Buscar");

        txtaPedidoFP.setColumns(20);
        txtaPedidoFP.setRows(5);
        scrpPedidoFP.setViewportView(txtaPedidoFP);

        btnFinalizarPedidoFP.setText("Finalizar Pedido");
        btnFinalizarPedidoFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoFPActionPerformed(evt);
            }
        });

        btnRegresarFP.setText("Regresar");
        btnRegresarFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarFPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameFinalizarPedidoLayout = new javax.swing.GroupLayout(FrameFinalizarPedido.getContentPane());
        FrameFinalizarPedido.getContentPane().setLayout(FrameFinalizarPedidoLayout);
        FrameFinalizarPedidoLayout.setHorizontalGroup(
            FrameFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameFinalizarPedidoLayout.createSequentialGroup()
                .addGroup(FrameFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameFinalizarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrpPedidoFP))
                    .addGroup(FrameFinalizarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtfPedidoFP, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPedidoFP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameFinalizarPedidoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblFinalizarPedido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameFinalizarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresarFP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarPedidoFP)))
                .addContainerGap())
        );
        FrameFinalizarPedidoLayout.setVerticalGroup(
            FrameFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameFinalizarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinalizarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfPedidoFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPedidoFP))
                .addGap(18, 18, 18)
                .addComponent(scrpPedidoFP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameFinalizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarPedidoFP)
                    .addComponent(btnRegresarFP))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        FramePedidosPendientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                FramePedidosPendientesComponentShown(evt);
            }
        });

        lblPedidosPendientes.setText("Pedidos pendientes");

        txtaPedidosPP.setColumns(20);
        txtaPedidosPP.setRows(5);
        scrpPedidosPP.setViewportView(txtaPedidosPP);

        btnRegresarPP.setText("Regresar");
        btnRegresarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPPActionPerformed(evt);
            }
        });

        txtfPedidoRevisarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPedidoRevisarPPActionPerformed(evt);
            }
        });

        btnRevisarPP.setText("Revisar");
        btnRevisarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarPPActionPerformed(evt);
            }
        });

        lblPedidoRevisarPP.setText("Pedido a revisar");

        btnRegresarPedidosPP.setText("Regresar a Pedidos");
        btnRegresarPedidosPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPedidosPPActionPerformed(evt);
            }
        });

        btnEnviadoPP.setText("Enviado");
        btnEnviadoPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviadoPPActionPerformed(evt);
            }
        });

        lblPedidoEnviarPP.setText("Pedido a envar");

        javax.swing.GroupLayout FramePedidosPendientesLayout = new javax.swing.GroupLayout(FramePedidosPendientes.getContentPane());
        FramePedidosPendientes.getContentPane().setLayout(FramePedidosPendientesLayout);
        FramePedidosPendientesLayout.setHorizontalGroup(
            FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FramePedidosPendientesLayout.createSequentialGroup()
                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FramePedidosPendientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrpPedidosPP))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FramePedidosPendientesLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblPedidosPendientes)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FramePedidosPendientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FramePedidosPendientesLayout.createSequentialGroup()
                                .addComponent(btnRegresarPP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresarPedidosPP))
                            .addGroup(FramePedidosPendientesLayout.createSequentialGroup()
                                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPedidoRevisarPP)
                                    .addComponent(lblPedidoEnviarPP))
                                .addGap(18, 18, 18)
                                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfPedidoRevisarPP, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txtfPedidoEnviarPP))
                                .addGap(18, 18, 18)
                                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnviadoPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRevisarPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        FramePedidosPendientesLayout.setVerticalGroup(
            FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePedidosPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedidosPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpPedidosPP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedidoRevisarPP)
                    .addComponent(txtfPedidoRevisarPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevisarPP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviadoPP)
                    .addComponent(lblPedidoEnviarPP)
                    .addComponent(txtfPedidoEnviarPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(FramePedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPP)
                    .addComponent(btnRegresarPedidosPP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setText("Menu inicial");

        btnFrameRegistrarPedido.setText("Registrar Pedido");
        btnFrameRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarPedidoActionPerformed(evt);
            }
        });

        btnFrameRegistrarCliente.setText("Registrar Cliente");
        btnFrameRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarClienteActionPerformed(evt);
            }
        });

        btnFrameCancelarPedido.setText("Cancelar Pedido");
        btnFrameCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameCancelarPedidoActionPerformed(evt);
            }
        });

        btnFrameGenerarReporte.setText("Generar reporte de Pedido");
        btnFrameGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameGenerarReporteActionPerformed(evt);
            }
        });

        btnFrameEditarPedido.setText("Editar Pedido");
        btnFrameEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameEditarPedidoActionPerformed(evt);
            }
        });

        btnFrameFinalizarPedido.setText("Finalizar Pedido");
        btnFrameFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameFinalizarPedidoActionPerformed(evt);
            }
        });

        btnFramePedidosPendientes.setText("Pedidos pendientes");
        btnFramePedidosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFramePedidosPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMenu)
                    .addComponent(btnFrameRegistrarPedido)
                    .addComponent(btnFrameRegistrarCliente)
                    .addComponent(btnFrameCancelarPedido)
                    .addComponent(btnFrameGenerarReporte)
                    .addComponent(btnFrameEditarPedido)
                    .addComponent(btnFrameFinalizarPedido)
                    .addComponent(btnFramePedidosPendientes))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarCliente)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameCancelarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameEditarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameFinalizarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFramePedidosPendientes)
                .addGap(18, 18, 18)
                .addComponent(btnFrameGenerarReporte)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrameRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        FrameRegistrarPedido.setSize(WIDTH+50, HEIGHT+300);
        FrameRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarPedidoActionPerformed

    private void btnFrameRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarClienteActionPerformed
        // TODO add your handling code here:
        FrameRegistrarCliente.setSize(WIDTH, HEIGHT);
        FrameRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarClienteActionPerformed

    private void btnFrameCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameCancelarPedidoActionPerformed
        // TODO add your handling code here:
        FrameCancelarPedido.setSize(WIDTH, HEIGHT);
        FrameCancelarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameCancelarPedidoActionPerformed

    private void btnFrameGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameGenerarReporteActionPerformed
        // TODO add your handling code here:
        FrameGenerarReporte.setSize(WIDTH, HEIGHT-100);
        FrameGenerarReporte.setVisible(true);
    }//GEN-LAST:event_btnFrameGenerarReporteActionPerformed

    private void txtfClienteRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteRPActionPerformed

    private void txtfClienteCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteCPActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void cmbbPeriodoGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbPeriodoGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbPeriodoGRActionPerformed

    private void btnFrameEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameEditarPedidoActionPerformed
        // TODO add your handling code here:
        FrameEditarPedido.setSize(WIDTH, HEIGHT);
        FrameEditarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameEditarPedidoActionPerformed

    private void txtfPedidoEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPedidoEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPedidoEPActionPerformed

    private void txtfProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProductoRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProductoRPActionPerformed

    private void btnRegresarRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRCActionPerformed
        // TODO add your handling code here:
        txtfNombreRC.setText("");
        txtfTelefonoRC.setText("");
        txtfDireccionRC.setText("");
        lblNumeroIdentificacionRC.setText("Número identificador:");
        FrameRegistrarCliente.setVisible(false);
    }//GEN-LAST:event_btnRegresarRCActionPerformed

    private void btnRegresarRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarRPActionPerformed
        // TODO add your handling code here:
        mostrarRegistrarPedido();
        FrameRegistrarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarRPActionPerformed

    private void btnRegresarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCPActionPerformed
        // TODO add your handling code here:
        FrameCancelarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarCPActionPerformed

    private void btnRegresarGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarGRActionPerformed
        // TODO add your handling code here:
        FrameGenerarReporte.setVisible(false);
    }//GEN-LAST:event_btnRegresarGRActionPerformed

    private void btnRegresarEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEPActionPerformed
        // TODO add your handling code here:
        FrameEditarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarEPActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente.setNombre(txtfNombreRC.getText());
        cliente.setDireccion(txtfDireccionRC.getText());
        cliente.setTelefono(txtfTelefonoRC.getText());
        cliente.setClave(txtfTelefonoRC.getText());
        
        // Agregar cliente a arraylist
        if(cliente.validarCliente()) {
            clientes.add(cliente);
            lblNumeroIdentificacionRC.setText("Número identificador: "+cliente.getClave());
        } else {
            lblNumeroIdentificacionRC.setText("Llena todos los campos");
        }
        //FrameRegistrarCliente.setVisible(false);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnComprobarClienteRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarClienteRPActionPerformed
        // TODO add your handling code here:
        String idCliente = txtfClienteRP.getText();
        if(idCliente==null) {
            lblNombreClienteRP.setText("INTRODUCE UN IDENTIFICADOR");
        } else {
            Cliente cliente = new Cliente();

            //BUSCAR EL CLIENTE EN LA BD
            for(int i=0; i<clientes.size(); ++i) {
                if(idCliente.equals(clientes.get(i).getClave())) {
                    cliente = clientes.get(i);
                    break;
                }
            }

            if (cliente.validarCliente()) {
                lblNombreClienteRP.setText("Nombre: "+cliente.getNombre());
                lblTelefonoClienteRP.setText("Teléfono: "+cliente.getTelefono());
                lblDireccionClienteRP.setText("Dirección: "+cliente.getDireccion());
            } else {
                lblNombreClienteRP.setText("IDENTIFICADOR NO VALIDO");
            }
        }
    }//GEN-LAST:event_btnComprobarClienteRPActionPerformed

    private void btnComprobarProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarProductoRPActionPerformed
        // TODO add your handling code here:
        String idProducto = txtfProductoRP.getText();
        Producto producto = new Producto();
        
        //BUSCAR EL PRODUCTO EN EL ARRAYLIST
        for(int i=0; i<productos.size(); ++i) {
            
            if(idProducto.equals(productos.get(i).getClave())) {
                producto = productos.get(i);
                break;
            }
        }
        
        lblNombreProductoRP.setText("Nombre: "+producto.getNombre());
        lblCantidadProductoRP.setText("Stock: "+Integer.toString(producto.getCantidad()));
        lblPrecioProductoRP.setText(Integer.toString(producto.getPrecio()));
    }//GEN-LAST:event_btnComprobarProductoRPActionPerformed

    private void btnAgregarProductoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoRPActionPerformed
        // TODO add your handling code here:
        Pedido pedido;
        if(pedidos.size() == clavePedidos) {
            pedido = new Pedido();
            pedidos.add(pedido);
        } else {
            pedido = pedidos.get(clavePedidos);
        }
            
        Producto producto = new Producto();
        String idProducto = txtfProductoRP.getText();
        int cantidad = Integer.parseInt(txtfCantidadRP.getText());
        
        for(int i=0; i<productos.size(); ++i) {
            if(idProducto.equals(productos.get(i).getClave())) {
                producto = productos.get(i);
                break;
            }
        }
        
        pedido.setClaveProducto(producto);
        pedido.setCantidadProducto(cantidad);
        int total = pedido.getTotal()+(producto.getPrecio()*cantidad);
        pedido.setTotal(total);
        lblPrecioPedidoRP.setText(Integer.toString(total));
        txtaPedidosRP.append(producto.getNombre()+
                             "\t\t"+cantidad+
                             "\t\t"+"$ "+Integer.toString(producto.getPrecio())+"\n");
        
        //++numProdPedido;
        int stock = producto.getCantidad();
        producto.setCantidad(stock-cantidad);
    }//GEN-LAST:event_btnAgregarProductoRPActionPerformed

    private void btnRegistrarPedidoRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedidoRPActionPerformed
        // TODO add your handling code here:
        int sizePedido = pedidos.size();
        Pedido pedido = pedidos.get(sizePedido-1);
        
        ++clavePedidos;
        lblIdentificadorPedidoRP.setText("Identificador del Pedido: "+Integer.toString(clavePedidos));
        pedido.setClave(Integer.toString(clavePedidos));
        pedido.setClaveCliente(txtfClienteRP.getText());
        
        pedido.setEstado("pendiente");
        //numProdPedido = 0;
        
        //FrameRegistrarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegistrarPedidoRPActionPerformed

    private void btnBuscarClienteCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteCPActionPerformed
        
    }//GEN-LAST:event_btnBuscarClienteCPActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnFrameFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameFinalizarPedidoActionPerformed
        // TODO add your handling code here:
        FrameFinalizarPedido.setSize(WIDTH, HEIGHT);
        FrameFinalizarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameFinalizarPedidoActionPerformed

    private void btnFramePedidosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFramePedidosPendientesActionPerformed
        // TODO add your handling code here:
        FramePedidosPendientes.setSize(WIDTH, HEIGHT);
        FramePedidosPendientes.setVisible(true);
    }//GEN-LAST:event_btnFramePedidosPendientesActionPerformed

    private void txtfPedidoFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPedidoFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPedidoFPActionPerformed

    private void btnFinalizarPedidoFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarPedidoFPActionPerformed

    private void btnRegresarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPPActionPerformed
        // TODO add your handling code here:
        txtaPedidosPP.setText("");
        txtfPedidoRevisarPP.setText("");
        txtfPedidoEnviarPP.setText("");
        FramePedidosPendientes.setVisible(false);
    }//GEN-LAST:event_btnRegresarPPActionPerformed

    private void btnRevisarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarPPActionPerformed
        // TODO add your handling code here:
        txtaPedidosPP.setText("");
        String idPedido = txtfPedidoRevisarPP.getText();
        Pedido pedido = new Pedido();
        
        for(int i=0; i<pedidos.size(); ++i) {
            if(idPedido.equals(pedidos.get(i).getClave())) {
                pedido = pedidos.get(i);
                break;
            }
        }
        
        //Desplegar datos de pedido en text area
        txtfPedidoRevisarPP.setText("");
        txtaPedidosPP.append("# Pedido: "+pedido.getClave()+"\n");
        txtaPedidosPP.append("Cliente: "+pedido.getClaveCliente()+"\n");
        txtaPedidosPP.append("Productos:\n");
        for(int i=0; i<pedido.getSizeProductos(); ++i) {
            txtaPedidosPP.append(pedido.getClaveProducto(i).getNombre()+
                                 "\t"+
                                 Integer.toString(pedido.getCantidadProducto(i))+"\n");
        }
        txtaPedidosPP.append("Total: $"+Integer.toString(pedido.getTotal())+"\n");
    }//GEN-LAST:event_btnRevisarPPActionPerformed

    private void btnRegresarFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarFPActionPerformed
        // TODO add your handling code here:
        FrameFinalizarPedido.setVisible(false);
    }//GEN-LAST:event_btnRegresarFPActionPerformed

    private void txtfCantidadRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCantidadRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCantidadRPActionPerformed

    private void txtfPedidoRevisarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPedidoRevisarPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPedidoRevisarPPActionPerformed

    private void FramePedidosPendientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_FramePedidosPendientesComponentShown
        // TODO add your handling code here:
        mostrarPedidosPendientes();
    }//GEN-LAST:event_FramePedidosPendientesComponentShown

    private void btnEnviadoPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviadoPPActionPerformed
        // TODO add your handling code here:
        String idPedido = txtfPedidoEnviarPP.getText();
        Pedido pedido = new Pedido();
        for(int i=0; i<pedidos.size(); ++i) {
            pedido = pedidos.get(i);
            if(idPedido.equals(pedido.getClave())) {
                pedido.setEstado("enviado");
                break;
            }
        }
        mostrarPedidosPendientes();
    }//GEN-LAST:event_btnEnviadoPPActionPerformed

    private void btnRegresarPedidosPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPedidosPPActionPerformed
        // TODO add your handling code here:
        mostrarPedidosPendientes();
    }//GEN-LAST:event_btnRegresarPedidosPPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarRegistrarPedido();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarPedidosPendientes() {
        txtaPedidosPP.setText("");
                
        Pedido pedido = new Pedido();
        for(int i=0; i<pedidos.size(); ++i) {
            pedido = pedidos.get(i);
            if(pedido.getEstado().equals("pendiente")) {
                txtaPedidosPP.append("# Pedido: "+pedido.getClave()+"\t"+
                                     "Cliente: "+pedido.getClaveCliente()+"\n");
            }
        }
    }
    
    private void mostrarRegistrarPedido() {
        txtfClienteRP.setText("");
        txtfProductoRP.setText("");
        txtfCantidadRP.setText("");
        txtaPedidosRP.setText("");
        lblNombreClienteRP.setText("Nombre:");
        lblTelefonoClienteRP.setText("Teléfono:");
        lblDireccionClienteRP.setText("Dirreción:");
        lblNombreProductoRP.setText("Nombre:");
        lblCantidadProductoRP.setText("Stock:");
        lblPrecioProductoRP.setText("Precio");
        lblPrecioPedidoRP.setText("Precio");
        lblIdentificadorPedidoRP.setText("Identificador del Pedido:");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameCancelarPedido;
    private javax.swing.JFrame FrameEditarPedido;
    private javax.swing.JFrame FrameFinalizarPedido;
    private javax.swing.JFrame FrameGenerarReporte;
    private javax.swing.JFrame FramePedidosPendientes;
    private javax.swing.JFrame FrameRegistrarCliente;
    private javax.swing.JFrame FrameRegistrarPedido;
    private javax.swing.JButton btnAgregarProductoEP;
    private javax.swing.JButton btnAgregarProductoRP;
    private javax.swing.JButton btnBuscarClienteCP;
    private javax.swing.JButton btnBuscarPedidoEP;
    private javax.swing.JButton btnBuscarPedidoFP;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnComprobarClienteRP;
    private javax.swing.JButton btnComprobarProductoRP;
    private javax.swing.JButton btnEliminarProductoEP;
    private javax.swing.JButton btnEnviadoPP;
    private javax.swing.JButton btnFinalizarPedidoFP;
    private javax.swing.JButton btnFrameCancelarPedido;
    private javax.swing.JButton btnFrameEditarPedido;
    private javax.swing.JButton btnFrameFinalizarPedido;
    private javax.swing.JButton btnFrameGenerarReporte;
    private javax.swing.JButton btnFramePedidosPendientes;
    private javax.swing.JButton btnFrameRegistrarCliente;
    private javax.swing.JButton btnFrameRegistrarPedido;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarPedidoRP;
    private javax.swing.JButton btnRegresarCP;
    private javax.swing.JButton btnRegresarEP;
    private javax.swing.JButton btnRegresarFP;
    private javax.swing.JButton btnRegresarGR;
    private javax.swing.JButton btnRegresarPP;
    private javax.swing.JButton btnRegresarPedidosPP;
    private javax.swing.JButton btnRegresarRC;
    private javax.swing.JButton btnRegresarRP;
    private javax.swing.JButton btnRevisarPP;
    private javax.swing.JComboBox<String> cmbbPeriodoGR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCancelarPedido;
    private javax.swing.JLabel lblCantidadPedidoRP;
    private javax.swing.JLabel lblCantidadProductoRP;
    private javax.swing.JLabel lblDineroPedidoRP;
    private javax.swing.JLabel lblDineroProductoRP;
    private javax.swing.JLabel lblDireccionClienteRP;
    private javax.swing.JLabel lblDireccionRC;
    private javax.swing.JLabel lblEditarPedido;
    private javax.swing.JLabel lblFinalizarPedido;
    private javax.swing.JLabel lblGenerarReporte;
    private javax.swing.JLabel lblIdentificadorPedidoRP;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreClienteRP;
    private javax.swing.JLabel lblNombreProductoRP;
    private javax.swing.JLabel lblNombreRC;
    private javax.swing.JLabel lblNumeroIdentificacionRC;
    private javax.swing.JLabel lblPedidoEnviarPP;
    private javax.swing.JLabel lblPedidoRevisarPP;
    private javax.swing.JLabel lblPedidosPendientes;
    private javax.swing.JLabel lblPeriodoRevisarGR;
    private javax.swing.JLabel lblPrecioPedidoRP;
    private javax.swing.JLabel lblPrecioProductoPedidoRP;
    private javax.swing.JLabel lblPrecioProductoRP;
    private javax.swing.JLabel lblProductoPedidoRP;
    private javax.swing.JLabel lblRegistrarCliente;
    private javax.swing.JLabel lblRegistrarPedido;
    private javax.swing.JLabel lblTelefonoClienteRP;
    private javax.swing.JLabel lblTelefonoRC;
    private javax.swing.JLabel lblTotalPedidoRP;
    private javax.swing.JScrollPane scrpPedidoEP;
    private javax.swing.JScrollPane scrpPedidoFP;
    private javax.swing.JScrollPane scrpPedidosCP;
    private javax.swing.JScrollPane scrpPedidosPP;
    private javax.swing.JScrollPane scrpPedidosRP;
    private javax.swing.JTextArea txtaPedidoEP;
    private javax.swing.JTextArea txtaPedidoFP;
    private javax.swing.JTextArea txtaPedidosCP;
    private javax.swing.JTextArea txtaPedidosPP;
    private javax.swing.JTextArea txtaPedidosRP;
    private javax.swing.JTextField txtfAgregarProductoEP;
    private javax.swing.JTextField txtfCantidadProductoEP;
    private javax.swing.JTextField txtfCantidadRP;
    private javax.swing.JTextField txtfClienteCP;
    private javax.swing.JTextField txtfClienteRP;
    private javax.swing.JTextField txtfDireccionRC;
    private javax.swing.JTextField txtfEliminarProductoEP;
    private javax.swing.JTextField txtfNombreRC;
    private javax.swing.JTextField txtfPedidoCancelarCP;
    private javax.swing.JTextField txtfPedidoEP;
    private javax.swing.JTextField txtfPedidoEnviarPP;
    private javax.swing.JTextField txtfPedidoFP;
    private javax.swing.JTextField txtfPedidoRevisarPP;
    private javax.swing.JTextField txtfProductoRP;
    private javax.swing.JTextField txtfTelefonoRC;
    // End of variables declaration//GEN-END:variables

}
