/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.uam.azc.p_soft_omega;

/**
 *
 * @author Santiago PG
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameRegistrarPedido = new javax.swing.JFrame();
        lblRegistrarPedido = new javax.swing.JLabel();
        lblClienteRP = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnComprobarRP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblNombreClienteRP = new javax.swing.JLabel();
        lblTelefonoClienteRP = new javax.swing.JLabel();
        lblDireccionClienteRP = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPrecioProductoRP = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FrameRegistrarCliente = new javax.swing.JFrame();
        lblRegistrarCliente = new javax.swing.JLabel();
        lblNombreRC = new javax.swing.JLabel();
        txtfNombreRC = new javax.swing.JTextField();
        lblTelefonoRC = new javax.swing.JLabel();
        txtfTelefonoRC = new javax.swing.JTextField();
        txtfDireccionRC = new javax.swing.JTextField();
        lblDireccionRC = new javax.swing.JLabel();
        btnRegresarRC = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        lblNumeroIdentificacionRC = new javax.swing.JLabel();
        FrameCancelarPedido = new javax.swing.JFrame();
        lblCancelarPedido = new javax.swing.JLabel();
        txtfClienteCP = new javax.swing.JTextField();
        btnBuscarClienteCP = new javax.swing.JButton();
        scrpPedidosCP = new javax.swing.JScrollPane();
        btnCancelarPedido = new javax.swing.JButton();
        btnRegresarCP = new javax.swing.JButton();
        FrameGenerarReporte = new javax.swing.JFrame();
        lblGenerarReporte = new javax.swing.JLabel();
        cmbbPeriodoGR = new javax.swing.JComboBox<>();
        lblPeriodoRevisarGR = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        btnRegresarGR = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        btnFrameRegistrarPedido = new javax.swing.JButton();
        btnFrameRegistrarCliente = new javax.swing.JButton();
        btnFrameCancelarPedido = new javax.swing.JButton();
        btnFrameGenerarReporte = new javax.swing.JButton();

        lblRegistrarPedido.setText("Registro de Pedido");

        lblClienteRP.setText("Identificador del Cliente");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnComprobarRP.setText("Comprobar");

        jLabel3.setText("Identificador del Producto");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprobar");

        jLabel4.setText("Ingresa cantidad");

        jLabel5.setText("Producto");

        jLabel6.setText("Cantidad");

        jLabel7.setText("Precio");

        jLabel8.setText("Subtotal");

        jLabel9.setText("Total:");

        jButton4.setText("Agregar Producto");

        jButton5.setText("Finalizar Pedido");

        jButton10.setText("Regresar");

        lblNombreClienteRP.setText("Nombre:");

        lblTelefonoClienteRP.setText("Telefono:");

        lblDireccionClienteRP.setText("Direccion:");

        jLabel13.setText("Nombre:");

        jLabel14.setText("Cantidad:");

        jLabel16.setText("$");

        jLabel17.setText("Precio");

        jLabel18.setText("$");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout FrameRegistrarPedidoLayout = new javax.swing.GroupLayout(FrameRegistrarPedido.getContentPane());
        FrameRegistrarPedido.getContentPane().setLayout(FrameRegistrarPedidoLayout);
        FrameRegistrarPedidoLayout.setHorizontalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addComponent(lblClienteRP)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprobarRP))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(74, 74, 74)
                                                .addComponent(jLabel7))
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblPrecioProductoRP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton3))))
                            .addComponent(jScrollPane1)
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(lblNombreClienteRP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(lblTelefonoClienteRP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                                        .addComponent(lblDireccionClienteRP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistrarPedido)
                .addGap(167, 167, 167))
        );
        FrameRegistrarPedidoLayout.setVerticalGroup(
            FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarPedidoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblRegistrarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteRP)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobarRP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreClienteRP)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoClienteRP)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionClienteRP)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPrecioProductoRP)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(25, 25, 25)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton10))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblRegistrarCliente.setText("Registro de Cliente");

        lblNombreRC.setText("Nombre:");

        lblTelefonoRC.setText("Teléfono:");

        lblDireccionRC.setText("Dirección:");

        btnRegresarRC.setText("Registrar Cliente");

        btnRegistrarCliente.setText("Regresar");

        lblNumeroIdentificacionRC.setText("Número de identificación");

        javax.swing.GroupLayout FrameRegistrarClienteLayout = new javax.swing.GroupLayout(FrameRegistrarCliente.getContentPane());
        FrameRegistrarCliente.getContentPane().setLayout(FrameRegistrarClienteLayout);
        FrameRegistrarClienteLayout.setHorizontalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreRC)
                                    .addComponent(lblTelefonoRC))
                                .addGap(18, 18, 18)
                                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfTelefonoRC)
                                    .addComponent(txtfNombreRC)))
                            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                                .addComponent(lblDireccionRC)
                                .addGap(18, 18, 18)
                                .addComponent(txtfDireccionRC))))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumeroIdentificacionRC)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameRegistrarClienteLayout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(lblRegistrarCliente)
                        .addGap(157, 157, 157))
                    .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                        .addComponent(btnRegistrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarRC)
                        .addContainerGap())))
        );
        FrameRegistrarClienteLayout.setVerticalGroup(
            FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameRegistrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarCliente)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRC)
                    .addComponent(txtfNombreRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoRC)
                    .addComponent(txtfTelefonoRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionRC)
                    .addComponent(txtfDireccionRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNumeroIdentificacionRC)
                .addGap(18, 18, 18)
                .addGroup(FrameRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(btnRegresarRC))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        lblCancelarPedido.setText("Cancelación de Pedido");

        txtfClienteCP.setText("Identificador del cliente");
        txtfClienteCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClienteCPActionPerformed(evt);
            }
        });

        btnBuscarClienteCP.setText("Buscar");

        btnCancelarPedido.setText("Cancelar pedido");

        btnRegresarCP.setText("Regresar");

        javax.swing.GroupLayout FrameCancelarPedidoLayout = new javax.swing.GroupLayout(FrameCancelarPedido.getContentPane());
        FrameCancelarPedido.getContentPane().setLayout(FrameCancelarPedidoLayout);
        FrameCancelarPedidoLayout.setHorizontalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblCancelarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                        .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(btnBuscarClienteCP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrpPedidosCP)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCancelarPedidoLayout.createSequentialGroup()
                        .addComponent(btnRegresarCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido)))
                .addContainerGap())
        );
        FrameCancelarPedidoLayout.setVerticalGroup(
            FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCancelarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelarPedido)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfClienteCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteCP))
                .addGap(18, 18, 18)
                .addComponent(scrpPedidosCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameCancelarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPedido)
                    .addComponent(btnRegresarCP))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        lblGenerarReporte.setText("Generación de Reporte");

        cmbbPeriodoGR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbPeriodoGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbPeriodoGRActionPerformed(evt);
            }
        });

        lblPeriodoRevisarGR.setText("Periodo a revisar:");

        btnGenerarReporte.setText("Generar reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnRegresarGR.setText("Regresar");

        javax.swing.GroupLayout FrameGenerarReporteLayout = new javax.swing.GroupLayout(FrameGenerarReporte.getContentPane());
        FrameGenerarReporte.getContentPane().setLayout(FrameGenerarReporteLayout);
        FrameGenerarReporteLayout.setHorizontalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPeriodoRevisarGR)
                        .addGap(18, 18, 18)
                        .addComponent(cmbbPeriodoGR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblGenerarReporte)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegresarGR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarReporte)))
                .addContainerGap())
        );
        FrameGenerarReporteLayout.setVerticalGroup(
            FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGenerarReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGenerarReporte)
                .addGap(18, 18, 18)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbPeriodoGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeriodoRevisarGR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(FrameGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarReporte)
                    .addComponent(btnRegresarGR))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setText("Menu inicial");

        btnFrameRegistrarPedido.setText("Registrar Pedido");
        btnFrameRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarPedidoActionPerformed(evt);
            }
        });

        btnFrameRegistrarCliente.setText("Registrar Cliente");
        btnFrameRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameRegistrarClienteActionPerformed(evt);
            }
        });

        btnFrameCancelarPedido.setText("Cancelar Pedido");
        btnFrameCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameCancelarPedidoActionPerformed(evt);
            }
        });

        btnFrameGenerarReporte.setText("Generar reporte de Pedido");
        btnFrameGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrameGenerarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMenu)
                    .addComponent(btnFrameRegistrarPedido)
                    .addComponent(btnFrameRegistrarCliente)
                    .addComponent(btnFrameCancelarPedido)
                    .addComponent(btnFrameGenerarReporte))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameRegistrarCliente)
                .addGap(18, 18, 18)
                .addComponent(btnFrameCancelarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnFrameGenerarReporte)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrameRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        FrameRegistrarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarPedidoActionPerformed

    private void btnFrameRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameRegistrarClienteActionPerformed
        // TODO add your handling code here:
        FrameRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_btnFrameRegistrarClienteActionPerformed

    private void btnFrameCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameCancelarPedidoActionPerformed
        // TODO add your handling code here:
        FrameCancelarPedido.setVisible(true);
    }//GEN-LAST:event_btnFrameCancelarPedidoActionPerformed

    private void btnFrameGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrameGenerarReporteActionPerformed
        // TODO add your handling code here:
        FrameGenerarReporte.setVisible(true);
    }//GEN-LAST:event_btnFrameGenerarReporteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtfClienteCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClienteCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClienteCPActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void cmbbPeriodoGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbPeriodoGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbPeriodoGRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameCancelarPedido;
    private javax.swing.JFrame FrameGenerarReporte;
    private javax.swing.JFrame FrameRegistrarCliente;
    private javax.swing.JFrame FrameRegistrarPedido;
    private javax.swing.JButton btnBuscarClienteCP;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnComprobarRP;
    private javax.swing.JButton btnFrameCancelarPedido;
    private javax.swing.JButton btnFrameGenerarReporte;
    private javax.swing.JButton btnFrameRegistrarCliente;
    private javax.swing.JButton btnFrameRegistrarPedido;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegresarCP;
    private javax.swing.JButton btnRegresarGR;
    private javax.swing.JButton btnRegresarRC;
    private javax.swing.JComboBox<String> cmbbPeriodoGR;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCancelarPedido;
    private javax.swing.JLabel lblClienteRP;
    private javax.swing.JLabel lblDireccionClienteRP;
    private javax.swing.JLabel lblDireccionRC;
    private javax.swing.JLabel lblGenerarReporte;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreClienteRP;
    private javax.swing.JLabel lblNombreRC;
    private javax.swing.JLabel lblNumeroIdentificacionRC;
    private javax.swing.JLabel lblPeriodoRevisarGR;
    private javax.swing.JLabel lblPrecioProductoRP;
    private javax.swing.JLabel lblRegistrarCliente;
    private javax.swing.JLabel lblRegistrarPedido;
    private javax.swing.JLabel lblTelefonoClienteRP;
    private javax.swing.JLabel lblTelefonoRC;
    private javax.swing.JScrollPane scrpPedidosCP;
    private javax.swing.JTextField txtfClienteCP;
    private javax.swing.JTextField txtfDireccionRC;
    private javax.swing.JTextField txtfNombreRC;
    private javax.swing.JTextField txtfTelefonoRC;
    // End of variables declaration//GEN-END:variables
}
